"use client";
import { StaticPage, Section } from "../privacy/page";

export default function TermsPage() {
  return (
    <StaticPage title="Terms of Service" updated="March 2026">
      <Section title="1. Acceptance">
        By using Dhara News, you agree to these terms. If you do not agree, do not use the platform.
      </Section>
      <Section title="2. What we provide">
        Dhara News provides AI-aggregated and AI-verified news content for informational purposes.
        We make reasonable efforts to verify accuracy via automated systems, but we do not guarantee
        the accuracy, completeness, or timeliness of any content. Always cross-check critical
        information with primary sources.
      </Section>
      <Section title="3. Your account">
        You are responsible for maintaining the security of your account and password.
        You must be 13 years or older to create an account. You may not share accounts.
      </Section>
      <Section title="4. Acceptable use">
        You may not use Dhara News to: scrape content at scale without permission, redistribute
        aggregated content commercially, or attempt to circumvent our verification systems.
      </Section>
      <Section title="5. Content ownership">
        Original summaries and analysis generated by Dhara News are our intellectual property.
        Source article content belongs to the original publishers. We operate under fair use
        principles for news aggregation. Source links are always provided.
      </Section>
      <Section title="6. Limitation of liability">
        Dhara News is provided "as is." We are not liable for decisions made based on content
        published on this platform. Verify important information independently.
      </Section>
      <Section title="7. Changes">
        We may update these terms. Continued use of the platform constitutes acceptance.
      </Section>
      <Section title="8. Contact">
        legal@dhara.news
      </Section>
    </StaticPage>
  );
}
